#!groovy
node { // <1>
    echo 'Hello from Jenkinsfile' // <2> 
    stage('Build') {
        sh 'echo \'hallooooo\''
        sh 'pwd'
        checkout scm
        sh './jenkins/test.sh'
    }
}

node { // <2>
    echo 'Running robot tests' // <2> 
    stage('Phase 2') {
        //sh '/home/ossi/omenia/projects/zef/docker/oto/docker_start_oto.sh'
        sh 'hello 2'
    }
}
